# kubectl create secret generic quickstart-es-elastic-user --from-literal=elastic=changeme --dry-run=server -o yaml > 03Srilab-elasticSecret.yaml
# 
apiVersion: v1
data:
  elastic: Y2hhbmdlbWU=
kind: Secret
metadata:
  creationTimestamp: "2024-02-24T16:54:09Z"
  name: quickstart-es-elastic-user
  namespace: default
  uid: 8b7bbc25-fe50-4587-9acb-b5a11b654ef9
type: Opaque
