apiVersion: v1
kind: ConfigMap
metadata:
  name: srilab-fluentd-config
  namespace: default
data:
  entrypoint.sh: |
    #!/bin/sh
    fluent-gem install fluent-plugin-elasticsearch
    /usr/bin/fluentd --config /fluentd/etc/fluent.conf
  fluent.conf: |
    <source srilab.jbs.accesslog>
      @type tail
      path /apps/wildfly-30.0.1.Final/standalone/log/access_log.log
      pos_file /tmp/accesslog.pos
      tag srilab.jbs.accesslog
      <parse>    
        @type none    
      </parse>                  
    </source>                   
  
    <filter srilab.jbs.accesslog*>
      @type record_transformer
      <record>
      hostname ${hostname}
      </record>
    </filter>
                                                 
    <match srilab.jbs.accesslog*>                       
      @type elasticsearch
      hosts https://elastic:changeme@quickstart-es-http.default.svc.cluster.local:9200
      ssl_verify false
      ssl_version TLSv1_2
      reload_connections false
      reconnect_on_error true
      reload_on_failure true
      index_name indexname.srilab.jbs.accesslog
      type_name indextype.k8s.efk
      time_key time
      logstash_format true
      logstash_prefix k8s.efk.${tag}
      include_timestamp true 
      flush_interval 1s                                            
    </match>

    <source srilab.jbs.serverlog>                                                    
      @type tail 
      path /apps/wildfly-30.0.1.Final/standalone/log/server.log
      pos_file /tmp/serverlog.pos
      tag srilab.jbs.serverlog  
      <parse>                   
        @type none                                     
      </parse>                                         
    </source>

    <filter srilab.jbs.serverlog*>
      @type record_transformer
      <record>
      hostname ${hostname}
      </record>
    </filter>            
                                                   
    <match srilab.jbs.serverlog*>
      @type elasticsearch
      hosts https://elastic:changeme@quickstart-es-http.default.svc.cluster.local:9200
      ssl_verify false
      ssl_version TLSv1_2
      reload_connections false
      reconnect_on_error true
      reload_on_failure true
      index_name indexname.srilab.jbs.serverlog
      type_name indextype.k8s.efk
      time_key time
      logstash_format true
      logstash_prefix k8s.efk.${tag}
      include_timestamp true
      flush_interval 1s
    </match>
