apiVersion: apps/v1
kind: Deployment
metadata:
  name: srilabjboss
  labels:
    app: wildfly
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 1
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      volumes:
       - name: srilabjbosslog
         emptyDir: {}
       - name: srilab-fluentd-config
         configMap:
           name: srilab-fluentd-config
      containers:
       - name: fluentd
         image: fluentd:latest
         command:
#           - sleep
#           - infinite
           - /bin/sh
           - /fluentd/etc/entrypoint.sh
         securityContext:
           runAsUser: 0
           runAsGroup: 0
           allowPrivilegeEscalation: false
         volumeMounts:
           - name: srilabjbosslog
             mountPath: /apps/wildfly-30.0.1.Final/standalone/log
           - name:  srilab-fluentd-config
             mountPath:  /fluentd/etc
       - name: wildfly
         image: dockersri83/srilab:ubuntujre21wildfly3001-2.0
         volumeMounts:
           - name: srilabjbosslog
             mountPath: /apps/wildfly-30.0.1.Final/standalone/log
         resources:
          requests:
           cpu: "250m"
           memory: "256Mi"
          limits:
           cpu: "500m"
           memory: "512Mi"
         command: ["sh"]
         args: ["/apps/wildfly-30.0.1.Final/bin/standalone.sh", "-Djboss.bind.address=0.0.0.0"]
         ports:
          - name: http8080
            containerPort: 8080
          - name: mgmt9990
            containerPort: 9990

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wildfly
  name: srilabjbosssvc
spec:
  ipFamilies:
  - IPv4
  ports:
  - name: jbosshttp
    port: 8080
    protocol: TCP
    targetPort: http8080
  - name: jbossmgmt
    port: 9990
    protocol: TCP
    targetPort: mgmt9990
  selector:
    app: wildfly
  sessionAffinity: None
  type: LoadBalancer

